### ISSUE TITLE
OpenTelemetry_SDK in 0.30 implements opentelemetry::trace::Tracer, but you want opentelemetry::trace::tracer::Tracer

### ISSUE THREAD

**Issue by VCasecnikovs** [tokio-rs/tracing-opentelemetry#206]
### Version

0.30
├── tracing-opentelemetry v0.30.0
│   ├── once_cell v1.21.3
│   ├── opentelemetry v0.29.1
│   │   ├── futures-core v0.3.31
│   │   ├── futures-sink v0.3.31
│   │   ├── pin-project-lite v0.2.16
│   │   ├── thiserror v2.0.12 (*)
│   │   └── tracing v0.1.41 (*)
│   ├── opentelemetry_sdk v0.29.0
│   │   ├── futures-channel v0.3.31 (*)
│   │   ├── futures-executor v0.3.31 (*)
│   │   ├── futures-util v0.3.31 (*)
│   │   ├── glob v0.3.2
│   │   ├── opentelemetry v0.29.1 (*)
│   │   ├── percent-encoding v2.3.1
│   │   ├── rand v0.9.1 (*)
│   │   └── thiserror v2.0.12 (*)
│   ├── smallvec v1.15.0 (*)
│   ├── tracing v0.1.41 (*)
│   ├── tracing-core v0.1.33 (*)
│   ├── tracing-log v0.2.0 (*)
│   └── tracing-subscriber v0.3.19 (*)

├── opentelemetry v0.30.0
│   ├── futures-core v0.3.31
│   ├── futures-sink v0.3.31
│   ├── pin-project-lite v0.2.16
│   ├── thiserror v2.0.12
│   │   └── thiserror-impl v2.0.12 (proc-macro)
│   │       ├── proc-macro2 v1.0.95 (*)
│   │       ├── quote v1.0.40 (*)
│   │       └── syn v2.0.101 (*)
│   └── tracing v0.1.41 (*)

### Platform

Mac M1

### Description

Example code:
```
let stdout_exporter = StdoutSpanExporter::default();

    let provider = SdkTracerProvider::builder()
        .with_simple_exporter(opentelemetry_stdout::SpanExporter::default())
        .build();

    let tracer = provider.tracer("astrum-backend");

    let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
```

Throws:
```
error[E0277]: the trait bound `SdkTracer: opentelemetry::trace::tracer::Tracer` is not satisfied
   --> src/main.rs:55:64
    |
55  |     let telemetry = tracing_opentelemetry::layer().with_tracer(tracer);
    |                                                    ----------- ^^^^^^ the trait `opentelemetry::trace::tracer::Tracer` is not implemented for `SdkTracer`
    |                                                    |
    |                                                    required by a bound introduced by this call
    |
```

SdkTracer in 0.30 implements opentelemetry::trace::Tracer, but you want opentelemetry::trace::tracer::Tracer

```
impl opentelemetry::trace::Tracer for SdkTracer {
```

**Comment by cschramm** [comment]
`tracing-opentelemetry` 0.30 works with `opentelemetry` 0.29, but you're using 0.30.0.

**Comment by mladedav** [comment]
You were mixing `tracing-opentelemetry@0.30` and `opentelemetry@0.30` which are not compatible.
